# AI-CRM Bot Configuration with Dialogue Analysis
# Основные параметры теперь берутся из .env файла
# Здесь только сообщения, промпты и расширенные настройки

messages:
  welcome: |
    🤖 Добро пожаловать в AI-CRM бот!
    
    Я помогу вам с информацией о наших услугах.
    Напишите мне что-нибудь!
    
  help: |
    ℹ️ Помощь:
    
    /start - начать работу
    /help - справка
    /menu - главное меню
    
  menu: |
    📋 Главное меню:
    
    Выберите действие.
    
  contact: |
    📞 Контакты:
    
    • Telegram: @support
    • Email: support@example.com
    
  error: "❌ Ошибка. Попробуйте позже."

# Промпты для AI анализа
prompts:
  # Индивидуальный анализ пользователя
  analyze_interest: |
    Оцени заинтересованность в покупке по шкале 0-100.
    
    Высокий интерес: купить, заказать, цена
    Средний интерес: интересно, подойдет
    Низкий интерес: дорого, не нужно
    
    Сообщение: "{message}"
    Контекст: {context}
    
    Ответь только числом 0-100.
    
  generate_response: |
    Ты - помощник CRM бота.
    
    Ответь вежливо и профессионально.
    Если высокий интерес - направляй к покупке.
    Ответ до 200 слов.
    
    Сообщение: "{message}"
    Интерес: {interest_score}/100
    
  analyze_lead: |
    Оцени потенциального клиента 0-100.
    
    Ищи проблемы, которые можем решить.
    
    Сообщение: "{message}"
    Канал: {channel}
    
    Ответь числом 0-100.

  # Новые промпты для анализа диалогов
  analyze_dialogue_context: |
    Ты - эксперт по анализу групповых диалогов потенциальных клиентов.
    
    Проанализируй диалог и определи:
    1. Есть ли покупательские намерения
    2. Кто принимает решения
    3. Влияние участников друг на друга
    4. Групповую динамику
    5. Скрытые потребности
    
    Диалог: {dialogue_text}
    Участники: {participants_info}
    
    Верни детальный JSON анализ с потенциальными лидами.
    
  identify_decision_makers: |
    Определи в диалоге:
    - Кто принимает решения (decision_maker)
    - Кто влияет на решения (influencer) 
    - Кто держит бюджет (budget_holder)
    - Кто просто наблюдает (observer)
    
    Диалог: {dialogue_text}
    
    Ответь JSON с ролями участников.
    
  analyze_group_buying_signals: |
    Найди в групповом диалоге сигналы готовности к покупке:
    - Обсуждение бюджета
    - Сравнение вариантов
    - Вопросы о сроках
    - Планирование внедрения
    - Поиск исполнителей
    
    Диалог: {dialogue_text}
    
    Оцени готовность группы к покупке 0-100.

# Настройки анализа диалогов
dialogue_analysis:
  # Паттерны для определения ролей участников
  role_patterns:
    decision_maker:
      - "принимаю решение"
      - "я решаю"
      - "моё решение"
      - "мой выбор"
      - "утверждаю"
      - "директор"
      - "руководитель"
      - "владелец"
    
    budget_holder:
      - "бюджет"
      - "деньги"
      - "финансы"
      - "оплата"
      - "стоимость"
      - "цена"
      - "финансовый"
      - "бухгалтер"
    
    influencer:
      - "рекомендую"
      - "советую"
      - "предлагаю"
      - "считаю что"
      - "на мой взгляд"
      - "эксперт"
      - "специалист"
      - "технический"
    
    observer:
      - "слушаю"
      - "интересно"
      - "понятно"
      - "хорошо"
      - "согласен"

  # Сигналы групповой готовности к покупке
  group_buying_signals:
    high_priority:
      - "когда можем начать"
      - "сроки внедрения"
      - "план проекта"
      - "договор"
      - "техническое задание"
      - "команда проекта"
    
    medium_priority:
      - "сравниваем варианты"
      - "рассматриваем предложения"
      - "изучаем рынок"
      - "анализируем решения"
      - "выбираем поставщика"
    
    budget_discussion:
      - "какой бюджет"
      - "сколько готовы потратить"
      - "стоимость проекта"
      - "финансирование"
      - "инвестиции"

  # Типы диалогов
  dialogue_types:
    price_inquiry: "Обсуждение цен и стоимости"
    feature_discussion: "Обсуждение функций и возможностей"
    competitor_comparison: "Сравнение с конкурентами"
    implementation_planning: "Планирование внедрения"
    technical_requirements: "Технические требования"
    support_request: "Запрос поддержки"
    complaint_resolution: "Решение проблем"

# Расширенные настройки AI
ai_settings:
  # Настройки анализа контекста
  context_analysis:
    weight_recent_messages: 0.7  # Вес последних сообщений
    weight_buying_signals: 0.8   # Вес покупательских сигналов
    weight_urgency_indicators: 0.9 # Вес индикаторов срочности
    
  # Пороги уверенности
  confidence_thresholds:
    hot_lead: 85      # Горячий лид
    warm_lead: 70     # Теплый лид
    cold_lead: 50     # Холодный лид
    dialogue_valuable: 75  # Ценный диалог
    
  # Настройки групповой динамики
  group_dynamics:
    min_interaction_score: 3  # Мин. уровень взаимодействия
    influence_threshold: 0.6  # Порог влияния
    consensus_indicator: 0.8  # Индикатор консенсуса

# Шаблоны уведомлений
notification_templates:
  individual_lead:
    title: "🎯 Новый потенциальный клиент"
    urgent_title: "🔥 СРОЧНО: Горячий лид!"
    
  dialogue_lead:
    title: "👥 Ценный групповой диалог"
    urgent_title: "🔥🔥 КРИТИЧНО: Группа готова к покупке!"
    
  analysis_summary:
    daily: "📊 Ежедневная сводка AI анализа"
    weekly: "📈 Недельный отчет по лидам"

# Настройки экспорта данных
export_settings:
  formats: ["csv", "json", "xlsx"]
  include_dialogue_context: true
  include_ai_analysis: true
  include_participant_roles: true
  anonymize_personal_data: false

# Настройки интеграций (для будущих версий)
integrations:
  webhook_url: null
  crm_sync: false
  analytics_platform: null
  
# Лимиты и ограничения
limits:
  max_active_dialogues: 100
  max_participants_per_dialogue: 20
  max_messages_per_dialogue: 200
  cache_size_limit: 1000
  analysis_timeout_seconds: 30