# AI-CRM Bot Configuration
# Основные параметры теперь берутся из .env файла
# Здесь только сообщения и промпты

messages:
  welcome: |
    🤖 Добро пожаловать в AI-CRM бот!
    
    Я помогу вам с информацией о наших услугах.
    Напишите мне что-нибудь!
    
  help: |
    ℹ️ Помощь:
    
    /start - начать работу
    /help - справка
    /menu - главное меню
    
  menu: |
    📋 Главное меню:
    
    Выберите действие.
    
  contact: |
    📞 Контакты:
    
    • Telegram: @support
    • Email: support@example.com
    
  error: "❌ Ошибка. Попробуйте позже."

prompts:
  analyze_interest: |
    Оцени заинтересованность в покупке по шкале 0-100.
    
    Высокий интерес: купить, заказать, цена
    Средний интерес: интересно, подойдет
    Низкий интерес: дорого, не нужно
    
    Сообщение: "{message}"
    Контекст: {context}
    
    Ответь только числом 0-100.
    
  generate_response: |
    Ты - помощник CRM бота.
    
    Ответь вежливо и профессионально.
    Если высокий интерес - направляй к покупке.
    Ответ до 200 слов.
    
    Сообщение: "{message}"
    Интерес: {interest_score}/100
    
  analyze_lead: |
    Оцени потенциального клиента 0-100.
    
    Ищи проблемы, которые можем решить.
    
    Сообщение: "{message}"
    Канал: {channel}
    
    Ответь числом 0-100.